;; This extracted scheme code relies on some additional macros
;; available at http://www.pps.univ-paris-diderot.fr/~letouzey/scheme
(load "macros_extr.scm")


(define add (lambdas (n m) (+ n m)))
  
(define mul (lambdas (n m) (* n m)))
  
(define sub (lambdas (n m) (if (< n m) 0 (- n m))))
  
(define eqb (lambdas (n m) (if (= n m) `(True) `(False))))
  
(define ltb (lambdas (n m) (if (< n m) `(True) `(False))))

(define buf_length (lambda (b) (bytes-len b)))

(define buf_get (lambdas (b i) (bytes-get b i)))

(define pure (lambdas (a st) `(Inl ,`(Pair ,st ,a))))

(define fail (lambdas (e _) `(Inr ,e)))

(define bind (lambdas (p f st)
  (match (p st)
     ((Inl p0) (match p0
                  ((Pair st~ a) (@ f a st~))))
     ((Inr e) `(Inr ,e)))))

(define read_u8 (lambda (st)
  (match (@ ltb (match st
                   ((Mk_pstate _ ps_off) ps_off))
           (buf_length (match st
                          ((Mk_pstate ps_buf _) ps_buf))))
     ((True) `(Inl ,`(Pair ,`(Mk_pstate
       ,(match st
           ((Mk_pstate ps_buf _) ps_buf))
       ,`((lambda (n) (+ n 1)) ,(match st
                                   ((Mk_pstate _ ps_off) ps_off))))
       ,(@ buf_get (match st
                      ((Mk_pstate ps_buf _) ps_buf))
          (match st
             ((Mk_pstate _ ps_off) ps_off))))))
     ((False) `(Inr ,`(UnexpectedEOF))))))

(define read_u16_be
  (@ bind read_u8 (lambda (hi)
    (@ bind read_u8 (lambda (lo)
      (pure
        (@ add
          (@ mul hi `((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
            ,`(0))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
          lo)))))))

(define guard (lambdas (b e)
  (match b
     ((True) (pure `(Tt)))
     ((False) (fail e)))))

(define at_end (lambda (st) `(Inl ,`(Pair ,st
  ,(@ eqb (match st
             ((Mk_pstate _ ps_off) ps_off))
     (buf_length (match st
                    ((Mk_pstate ps_buf _) ps_buf))))))))

(define read_bytes (lambda (n)
  ((lambdas (fO fS n) (if (= n 0) (fO 0) (fS (- n 1))))
     (lambda (_) (pure `(Nil)))
     (lambda (m)
     (@ bind read_u8 (lambda (b)
       (@ bind (read_bytes m) (lambda (rest) (pure `(Cons ,b ,rest)))))))
     n)))
  
(define parse_tlv (lambda (fuel)
  ((lambdas (fO fS n) (if (= n 0) (fO 0) (fS (- n 1))))
     (lambda (_) (fail `(UnexpectedEOF)))
     (lambda (fuel~)
     (@ bind read_u8 (lambda (tag)
       (@ bind read_u16_be (lambda (len)
         (match (@ eqb tag `((lambda (n) (+ n 1)) ,`(0)))
            ((True)
              (@ bind
                (@ guard
                  (@ eqb len `((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
                    ,`(0))))
                  `(BadLength))
                (lambda (_)
                (@ bind read_u16_be (lambda (v) (pure `(TlvU16 ,v)))))))
            ((False)
              (match (@ eqb tag `((lambda (n) (+ n 1))
                       ,`((lambda (n) (+ n 1)) ,`(0))))
                 ((True)
                   (@ bind (@ parse_tlv_seq fuel~ len) (lambda (items)
                     (pure `(TlvNested ,items)))))
                 ((False)
                   (match (@ eqb tag `((lambda (n) (+ n 1))
                            ,`((lambda (n) (+ n 1)) ,`((lambda (n) (+ n 1))
                            ,`(0)))))
                      ((True)
                        (@ bind (read_bytes len) (lambda (bs)
                          (pure `(TlvRaw ,bs)))))
                      ((False) (fail `(BadTag ,tag)))))))))))))
     fuel)))
  
(define parse_tlv_seq (lambdas (fuel remaining)
  ((lambdas (fO fS n) (if (= n 0) (fO 0) (fS (- n 1))))
     (lambda (_) (fail `(UnexpectedEOF)))
     (lambda (fuel~)
     (match (@ eqb remaining `(0))
        ((True) (pure `(Nil)))
        ((False) (lambda (st)
          (let ((start (match st
                          ((Mk_pstate _ ps_off) ps_off))))
            (match (@ parse_tlv fuel~ st)
               ((Inl p)
                 (match p
                    ((Pair st~ item)
                      (let ((consumed
                        (@ sub (match st~
                                  ((Mk_pstate _ ps_off) ps_off))
                          start)))
                        (match (@ ltb remaining consumed)
                           ((True) `(Inr ,`(BadLength)))
                           ((False)
                             (match (@ parse_tlv_seq fuel~
                                      (@ sub remaining consumed) st~)
                                ((Inl p0)
                                  (match p0
                                     ((Pair st~~ rest) `(Inl ,`(Pair ,st~~
                                       ,`(Cons ,item ,rest))))))
                                ((Inr e) `(Inr ,e)))))))))
               ((Inr e) `(Inr ,e))))))))
     fuel)))
  
(define parse_all (lambda (fuel)
  ((lambdas (fO fS n) (if (= n 0) (fO 0) (fS (- n 1))))
     (lambda (_) (pure `(Nil)))
     (lambda (fuel~)
     (@ bind at_end (lambda (done_)
       (match done_
          ((True) (pure `(Nil)))
          ((False)
            (@ bind (parse_tlv fuel~) (lambda (item)
              (@ bind (parse_all fuel~) (lambda (rest)
                (pure `(Cons ,item ,rest)))))))))))
     fuel)))
  
(define parse_buffer (lambdas (buf fuel)
  (@ parse_all fuel `(Mk_pstate ,buf ,`(0)))))

(define count_tlvs (lambda (items)
  (match items
     ((Nil) `(0))
     ((Cons _ rest) (@ add `((lambda (n) (+ n 1)) ,`(0)) (count_tlvs rest))))))
  
